title: Paresh Wagh
email: pawa2007@outlook.com
logo: https://avatars.githubusercontent.com/u/21964536?v=4
description: Odoo Configuration and Customization Expert
# theme: jekyll-theme-architect
remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one