title: Paresh Wagh
email: pawa2007@outlook.com
logo: https://avatars.githubusercontent.com/u/21964536?v=4
description: Odoo Configuration and Customization Expert
show_downloads: false
theme: jekyll-theme-cayman
